nordamerika_laender = [
    ("Antigua und Barbuda","Saint John's"),
    ("Bahamas", "Nassau"),
    ("Barbados", "Bridgetown"),
    ("Belize", "Belmopan"),
    ("Costa Rica", "San Jose"),
    ("Dominica", "Roseau"),
    ("Dominikanische Republik", "Santo Domingo"),
    ("Grenada", "St. George's"),
    ("El Salvador", "San Salvador"),
    ("Guatemala", "Guatemala-Stadt"),
    ("Haiti", "Port-au-Prince"),
    ("Honduras", "Tegucigalpa"),
    ("Jamaika", "Kingston"),
    ("Kanada", "Ottawa"),
    ("Kuba", "Havanna"),
    ("Mexiko", "Mexiko-Stadt"),
    ("Nicaragua", "Managua"),
    ("Panama", "Panama-Stadt"),
    ("St. Kitts und Nevis", "Basseterre"),
    ("St. Lucia", "Castries"),
    ("St. Vincent und die Grenadinen", "Kingstown"),
    ("Trinidad und Tobago", "Port of Spain"),
    ("USA", "Washington DC")
]

suedamerika_laender  = [
    ("Argentinien", "Buenos Aires"),
    ("Bolivien", "Sucre"),
    ("Brasilien", "Brasilia"),
    ("Chile", "Santiago de Chile"),
    ("Ecuador", "Quito"),
    ("Guyana", "Georgetown"),
    ("Kolumbien", "Bogota"),
    ("Paraguay", "Asuncion"),
    ("Peru", "Lima"),
    ("Surinam", "Paramaribo"),
    ("Uruguay", "Montevideo"),
    ("Venezuela", "Caracas")
]

afrika_laender  = [
    ("Ägypten", "Kairo"),
    ("Äquatorialguinea", "Malabo"),
    ("Algerien", "Algier"),
    ("Angola", "Luanda"),
    ("Äthiopien", "Addis Abeba"),
    ("Benin", "Porto-Novo"),
    ("Botswana", "Gaborone"),
    ("Burkina Faso", "Ouagadougou"),
    ("Burundi", "Gitega"),
    ("Dschibuti", "Dschibuti"),
    ("Elfenbeinküste", "Yamoussoukro"),
    ("Eritrea", "Asmara"),
    ("Eswatini", "Mbabane"),
    ("Gabun", "Libreville"),
    ("Gambia", "Banjul"),
    ("Ghana", "Accra"),
    ("Guinea", "Conakry"),
    ("Guinea-Bissau", "Bissau"),
    ("Kamerun", "Yaoundé"),
    ("Kap Verde", "Praia"),
    ("Kenia", "Nairobi"),
    ("Komoren", "Moroni"),
    ("Demokratische Republik Kongo", "Kinshasa"),
    ("Republik Kongo", "Brazzaville"),
    ("Lesotho", "Maseru"),
    ("Liberia", "Monrovia"),
    ("Libyen", "Tripolis"),
    ("Madagaskar", "Antananarivo"),
    ("Malawi", "Lilongwe"),
    ("Mali", "Bamako"),
    ("Marokko", "Rabat"),
    ("Mauretanien", "Nouakchott"),
    ("Mauritius", "Port Louis"),
    ("Mosambik", "Maputo"),
    ("Namibia", "Windhoek"),
    ("Niger", "Niamey"),
    ("Nigeria", "Abuja"),
    ("Ruanda", "Kigali"),
    ("Sambia", "Lusaka"),
    ("Sao Tome und Principe", "Sao Tome"),
    ("Senegal", "Dakar"),
    ("Seychellen", "Victoria"),
    ("Sierra Leone", "Freetown"),
    ("Simbabwe", "Harare"),
    ("Somalia", "Mogadischu"),
    ("Sudan", "Khartum"),
    ("Südafrika", "Pretoria/Kapstadt/Bloeamfontein"),
    ("Südsudan", "Juba"),
    ("Tansania", "Dodoma"),
    ("Togo", "Lomé"),
    ("Tschad", "N'Djamena"),
    ("Tunesien", "Tunis"),
    ("Uganda", "Kampala"),
    ("Zentralafrikanische Republik", "Bangui")
]

europa_laender  = [
    ("Albanien", "Tirana"),
    ("Andorra", "Andorra la Vella"),
    ("Belgien", "Brüssel"),
    ("Bosnien und Herzegowina", "Sarajevo"),
    ("Bulgarien", "Sofia"),
    ("Dänemark", "Kopenhagen"),
    ("Deutschland", "Berlin"),
    ("Estland", "Tallinn"),
    ("Finnland", "Helsinki"),
    ("Frankreich", "Paris"),
    ("Griechenland", "Athen"),
    ("Vereinigtes Königreich", "London"),
    ("Irland", "Dublin"),
    ("Island", "Reykjavik"),
    ("Italien", "Rom"),
    ("Kosovo", "Pristina"),
    ("Kroatien", "Zagreb"),
    ("Lettland", "Riga"),
    ("Liechtenstein", "Vaduz"),
    ("Litauen", "Vilnius"),
    ("Luxemburg", "Luxemburg"),
    ("Malta", "Valletta"),
    ("Moldawien", "Kischinau"),
    ("Monaco", "Monaco"),
    ("Montenegro", "Podgorica"),
    ("Niederlande", "Amsterdam"),
    ("Nordmazedonien", "Skopje"),
    ("Norwegen", "Oslo"),
    ("Österreich", "Wien"),
    ("Polen", "Warschau"),
    ("Portugal", "Lissabon"),
    ("Rumänien", "Bukarest"),
    ("Russland", "Moskau"),
    ("San Marino", "San Marino"),
    ("Schweden", "Stockholm"),
    ("Schweiz", "Bern"),
    ("Serbien", "Belgrad"),
    ("Slowakei", "Bratislava"),
    ("Slowenien", "Ljubljana"),
    ("Spanien", "Madrid"),
    ("Tschechien", "Prag"),
    ("Ukraine", "Kiew"),
    ("Ungarn", "Budapest"),
    ("Vatikanstadt", "Vatikanstadt"),
    ("Belarus", "Minsk"),
    ("Zypern", "Nikosia")
]

asien_laender  = [
    ("Afghanistan", "Kabul"),
    ("Armenien", "Eriwan"),
    ("Aserbaidschan", "Baku"),
    ("Bahrain", "Manama"),
    ("Bangladesch", "Dhaka"),
    ("Bhutan", "Thimphu"),
    ("Brunei", "Bandar Seri Begawan"),
    ("China", "Peking"),
    ("Georgien", "Tiflis"),
    ("Indien", "Neu-Delhi"),
    ("Indonesien", "Jakarta"),
    ("Irak", "Bagdad"),
    ("Iran", "Teheran"),
    ("Israel", "Jerusalem"),
    ("Japan", "Tokio"),
    ("Jemen", "Sanaa"),
    ("Jordanien", "Amman"),
    ("Kambodscha", "Phnom Penh"),
    ("Kasachstan", "Astana"),
    ("Katar","Doha"),
    ("Kirgisistan", "Bischkek"),
    ("Kuwait", "Kuwait-Stadt"),
    ("Laos", "Vientiane"),
    ("Libanon", "Beirut"),
    ("Malaysia", "Kuala Lumpur"),
    ("Malediven", "Malé"),
    ("Mongolei", "Ulaanbaatar"),
    ("Myanmar", "Naypyidaw"),
    ("Nepal", "Kathmandu"),
    ("Nordkorea", "Pjönjang"),
    ("Oman", "Maskat"),
    ("Ost-Timor", "Dili"),
    ("Pakistan", "Islamabad"),
    ("Palästina", "Ramallah/Ostjerusalem"),
    ("Philippinen", "Manila"),
    ("Saudi-Arabien", "Riad"),
    ("Singapur", "Singapur"),
    ("Sri Lanka", "Colombo"),
    ("Syrien", "Damaskus"),
    ("Südkorea", "Seoul"),
    ("Tadschikistan", "Duschanbe"),
    ("Thailand", "Bangkok"),
    ("Türkei", "Ankara"),
    ("Turkmenistan", "Aschgabat"),
    ("Usbekistan", "Taschkent"),
    ("Vereingite arabische Emirate", "Abu Dhabi"),
    ("Vietnam", "Hanoi")
]

ozeanien_laender  = [
    ("Australien", "Canberra"),
    ("Fidschi", "Suva"),
    ("Kiribati", "Tarawa"),
    ("Marshallinseln", "Majuro"),
    ("Mikronesien", "Palikir"),
    ("Nauru", "Yaren"),
    ("Neuseeland", "Wellington"),
    ("Palau", "Ngerulmud"),
    ("Papua-Neuguinea", "Port Moresby"),
    ("Salomonen", "Honiara"),
    ("Samoa", "Apia"),
    ("Tonga", "Nuku'alofa"),
    ("Tuvalu", "Funafuti"),
    ("Vanuatu", "Port Vila")
]